language: ruby
rvm:
  - 2.0.0
before_script:
  - gem update --system
  - bundle install
  - find . -name sass
  - cd frontend
  - npm install
  - npm install -g bower
  - npm install -g grunt-cli
  - bower cache clean
  - bower install
  - cd ..
script:
  - cd frontend
  - grunt test
  - cd ..
