language: node_js
node_js:
  - '0.10'

before_script:
  - 'rvm autolibs enable'
  - 'rvm reload'
  - 'rvm requirements'
  - 'rvm install 2.0.0'
  - 'rvm use 2.0.0'
  - 'gem update --system'
  - 'gem install compass'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
