language: ruby 
rvm:
  - 2.0.0
before_script:
  #- rvm autolibs enable
  #- rvm reload
  - export BUNDLE_GEMFILE=$PWD/backend/Gemfile
  - cd backend
  - bundle install
  - cd ../frontend
  - bundle exec compass
  - npm install
  - npm install -g bower
  - npm install -g grunt-cli
  - bower cache clean
  - bower install
  - cd ..
script:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - cd frontend
  - grunt test
  - cd ../backend
  - export BUNDLE_GEMFILE=$PWD/backend/Gemfile
  - rspec spec
