language: ruby
rvm:
  - 2.0.0
before_script:
  - PATH=$PATH:`pwd`/vendor/bundle/ruby/2.0.0/bin
  - find . -name "compass"
  - cd frontend
  - compass
  - echo $PATH
  - npm install
  - npm install -g bower
  - npm install -g grunt-cli
  - bower cache clean
  - bower install
  - cd ..
script:
  - cd frontend
  - grunt test
  - cd ..
