language: ruby
rvm:
  - 2.0.0
before_script:
  - rvm autolibs enable
  - rvm reload
  - bundle install
  - PATH=$PATH:`pwd`/vendor/bundle/ruby/2.0.0/bin
  - BUNDLE_PATH=`pwd`/vendor/bundle
#  - echo $PATH
#  - echo $GEM_HOME 
#  - echo $GEM_PATH
#  - echo $BUNDLE_PATH
#  - find . -name "compass"
  - cd frontend
  - compass
  - echo $PATH
  - npm install
  - npm install -g bower
  - npm install -g grunt-cli
  - bower cache clean
  - bower install
  - cd ..
script:
  - cd frontend
  - grunt test
  - cd ..
