language: ruby
rvm:
  - 2.0.0
before_script:
    - 'npm install -g yo'
    - 'gem update --system'
    - 'bundle install'
    - 'cd frontend'
    - 'bower cache clean'
    - 'bower install'
    - 'cd ..'
script:
    - 'cd frontend; grunt test; cd ..'


before_script:

